# SPDX-License-Identifier: Apache-2.0

name: 'Free Disk Space'
description: 'Frees disk space on the runner'
author: 'InstructLab, modified by benkirk'
runs:
  using: "composite"
  steps:
    - name: Print disk space before cleanup
      run: |
        df -h
      shell: bash
    - name: Free Disk Space
      shell: bash
      run: |
        # Determine if we have Ubuntu, CentOS, or other distro as our runner OS
        os_id=$(grep '^ID=' /etc/os-release | cut -d "=" -f2)

        TIMEFORMAT=$'--> Real time: %3R seconds'

        # If docker is installed, clean anythhing we can
        if command -v docker 2>&1 >/dev/null ; then
          echo "--------------------------------------------"
          echo "Cleaning Docker Caches:"
          echo "--------------------------------------------"
          sudo docker buildx du 2>/dev/null || true
          sudo docker buildx prune --force 2>/dev/null || true
          sudo docker image ls 2>/dev/null || true
          sudo docker system df 2>/dev/null || true
          sudo docker system prune --all --volumes --force 2>/dev/null || true
        fi

        probeUsage() {
          echo "--------------------------------------------"
          echo "Files: ${1}"
          echo "--------------------------------------------"
          for dir in /usr/local/bin /usr/bin; do
            sudo du --block-size=1M --threshold=$((9*1024*1024)) ${dir}/* | sort -n
          done
          echo "--------------------------------------------"
          echo "Directories: ${1}"
          echo "--------------------------------------------"
          for dir in /*/; do
            sudo du 2>/dev/null --max-depth=3 --block-size=1M --threshold=$((4*1024*1024)) --separate-dirs $(realpath ${dir}) | sort -n \
            || true
          done
        }

        # look for removal candidates
        # probeUsage "Before Cleanup"

        printWarningMessage () {
          echo "[warning] Failed to remove '$1', perhaps because it doesn't exist. Ignoring..."
        }

        # # Remove large packages we don't use.
        # echo "Attempting to remove unused ${os_id} packages..."
        # if [[ "${os_id}" =~ "ubuntu" ]]; then
        #   sudo apt-get remove -y \
        #     '^mysql-.*' \
        #     '^dotnet-.*' \
        #     'php.*' \
        #     '^llvm-.*' \
        #     'google-cloud-*' \
        #     --fix-missing || echo "ERROR removing packages..."
        #
        #   # for pkg in azure-cli microsoft-edge-stable google-chrome-stable powershell 'temurin-*' gh podman vim-runtime; do
        #   #   sudo apt-get remove -y ${pkg} --fix-missing || printWarningMessage "${pkg}"
        #   # done
        #   sudo apt-get autoremove -y >/dev/null 2>&1
        #   sudo apt-get autoclean -y >/dev/null 2>&1
        #
        #   echo "--------------------------------------------"
        #   echo Top remaining packages by size:
        #   echo "--------------------------------------------"
        #   dpkg-query --show --showformat='${Installed-Size} : ${Package}\n' 2>/dev/null | sort -rn | head -n 50 || true
        # fi

        # Remove a whole slew of unnecessary directories
        echo "----------------------------------------------------------------"
        echo "Brute-force Removing directories, headers, and static libraries."
        echo "----------------------------------------------------------------"
        set -x
        time sudo rm -rf \
          /opt/az \
          /opt/ghc \
          /opt/google*/ \
          /opt/hostedtoolcache \
          /opt/microsoft \
          /opt/pipx \
          /usr/bin/buildah \
          /usr/bin/podman \
          /usr/include/llvm-*/ \
          /usr/lib/dotnet \
          /usr/lib/firefox \
          /usr/lib/google-*/ \
          /usr/lib/jvm \
          /usr/lib/llvm-*/ \
          /usr/local/.ghcup \
          /usr/local/aws*/ \
          /usr/local/bin/*cmake* \
          /usr/local/bin/azcopy \
          /usr/local/bin/node \
          /usr/local/bin/pulumi* \
          /usr/local/doc \
          /usr/local/include/node \
          /usr/local/julia*/ \
          /usr/local/lib/android \
          /usr/local/lib/node_modules \
          /usr/local/n \
          /usr/local/share/chromium \
          /usr/local/share/powershell \
          /usr/local/share/vcpkg \
          /usr/share/az*/ \
          /usr/share/doc \
          /usr/share/dotnet \
          /usr/share/gradle*/ \
          /usr/share/icons \
          /usr/share/java \
          /usr/share/kotlinc \
          /usr/share/man \
          /usr/share/miniconda \
          /usr/share/ri \
          /usr/share/swift \
          /usr/share/vim \
          /var/cache \
          /var/lib/{apt,mysql,dpkg,waagent,gems,mecab}

        #sudo find /usr -type d -name "*azure*" -print0 | xargs -0 --no-run-if-empty sudo rm -rf
        time sudo find /usr /opt -type f -name "lib*.a" -print0 | xargs -0 --no-run-if-empty sudo rm -f
        time sudo find /usr /opt -type d -name "include" -print0 | xargs -0 --no-run-if-empty sudo rm -rf
        set +x

        # see what is left
        time probeUsage "After cleanup"

    - name: Print disk space after cleanup
      run: |
        df -h
      shell: bash
