# SPDX-License-Identifier: Apache-2.0

name: 'Free Docker Disk Space'
description: 'Frees disk space on the runner'
author: 'benkirk'
runs:
  using: "composite"
  steps:
    - name: Before Cleanup
      shell: bash
      run: |
        # Before Cleanup Docker
        echo "Docker System:"
        sudo docker image ls 2>/dev/null || true
        sudo docker volume ls 2>/dev/null || true
        sudo docker system df 2>/dev/null || true
        echo "Docker BuildX:"
        sudo docker buildx du 2>/dev/null || true
        df -h

    - name: Cleaning All Docker Images/Volumes/Caches
      shell: bash
      run: |
        # Cleanup Docker
        echo "--------------------------------------------"
        echo "Cleaning All Docker Images/Volumes/Caches"
        echo "--------------------------------------------"
        echo "Docker System:"
        sudo docker image prune --all --force 2>/dev/null || true
        sudo docker system prune --all --volumes --force 2>/dev/null || true
        echo "Docker BuildX:"
        sudo docker buildx prune --force 2>/dev/null || true
        sync

    - name: After Cleanup
      shell: bash
      run: |
        # After Cleanup Docker
        sudo docker system df 2>/dev/null || true
        df -h
