name: Conda Build

on:
  workflow_dispatch:
    inputs:
      hello_world:
        description: "Build Simple OpenMP Hello World"
        type: boolean
        default: true
  push:
    branches:
      - ci_cd

  schedule:
    # run at 2:42 UTC every Saturday
    # ref: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onschedule
    - cron: "42 2 * * 6"

jobs:
  build-from-conda-env:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    name: Build With Conda
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: bash -elo pipefail {0}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: demo-github-actions
          environment-file: conda.yaml

      - name: Interrogate Environment
        run: |
          conda list
          df -h
          cat /etc/os-release 2>/dev/null || true
          uname -a
          nvidia-smi 2>/dev/null || true
          free -g
          lscpu
          echo && echo && echo
          echo '----------------------------------------------------------------'
          echo && echo && echo
          echo "CC=${CC}"
          echo "CXX=${CXX}"
          echo "FC=${FC}"
          echo "F77=${F77}"
          echo
          echo "CFLAGS=${CFLAGS}"
          echo "CPPFLAGS=${CPPFLAGS}"
          echo "CXXFLAGS=${CXXFLAGS}"
          echo "FCFLAGS=${FCFLAGS}"
          echo "F77FLAGS=${F77FLAGS}"
          mpicc --version 2>/dev/null || true

      - name: List Source Tree
        run: |
          pwd
          find * ! -type d

      - name: Hello World
        if: ${{ inputs.hello_world }}
        run: |
          set -x
          ${CC} -o ./hello_world src/hello_world.c
          ldd ./hello_world
          ./hello_world

          ${FC} -o ./hello_world src/hello_world.f90
          ldd ./hello_world
          ./hello_world

          ${CXX} -o ./hello_world src/hello_world.cxx
          ldd ./hello_world
          ./hello_world

          ${CXX} -o ./hello_world_openmp src/hello_world.cxx -fopenmp
          ldd ./hello_world_openmp
          OMP_NUM_THREADS=4 ./hello_world_openmp
