name: Build Derived Container Images

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Container Build"]
    types: [completed]

jobs:
  build-my-containers:
    strategy:
      fail-fast: true
      matrix:
        compiler: [gcc12]
        mpi: [openmpi]

    name: Build Inside Container
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -elo pipefail {0}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          fetch-depth: 0

      - name: Interrogate Environment
        run: |
          cat /etc/os-release
          uname -a
          env | sort
          df -h
          lscpu

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Pre-build Query Docker Environment
        run: |
          which docker
          docker --version
          docker buildx ls
          docker buildx inspect
          docker buildx du

      - name: Build My Container
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: demorepo/myapp-${{ matrix.compiler }}-${{ matrix.mpi }}:latest
          context: containers/demo
          file: containers/demo/Dockerfile
          build-args: |
            BASE_IMAGE=benjaminkirk/cisldev-almalinux9-${{ matrix.compiler }}-${{ matrix.mpi }}:latest
          target: final
