name: Select HPC Development Container Image

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Base OS'
        type: choice
        required: true
        default: almalinux9
        options:
          - almalinux8
          - almalinux9
          - leap
          - tumbleweed
          - noble

      conda:
        description: 'Include Conda (Miniforge)'
        type: boolean
        required: false
        default: true

      compiler:
        description: 'Compiler'
        type: choice
        required: true
        default: os-gcc
        options:
          - os-gcc
          - gcc
          - oneapi
          - aocc
          - nvhpc
          - '<disabled>'

      compiler_version:
        description: 'Compiler Version'
        type: string
        required: false
        default: ''

      cuda:
        description: 'Include CUDA'
        type: boolean
        required: false
        default: false

      mpi:
        description: 'MPI'
        type: choice
        required: true
        default: openmpi
        options:
          - openmpi
          - mpich
          - mpich3
          - '<disabled>'

      mpi_version:
        description: 'MPI Version'
        type: string
        required: false
        default: ''

jobs:

  build-image:
    name: Build Container Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Create containers/devenv/extras
        run: |
          sudo apt-get update
          sudo apt-get install make
          which make
          pwd
          ls
          make -C containers/devenv extras

      - name: Interrogate Environment
        run: |
          cat /etc/os-release
          uname -a
          env | sort
          df -h
          lscpu

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.BENKIRK_DOCKERHUB_USERNAME }}
          password: ${{ secrets.BENKIRK_DOCKERHUB_TOKEN }}

      - name: Query Docker Environment
        run: |
          which docker
          docker --version
          docker buildx ls
          docker buildx inspect
          docker buildx du

      - name: Base OS - Cache SHA
        run: |
          cat << EOF > build_inputs.txt
          os: '${{ inputs.os }}'
          conda: '${{ inputs.conda }}'
          EOF
          echo && echo "Build Inputs:" && cat build_inputs.txt
          shasum build_inputs.txt > inputs_sha.txt
          cat inputs_sha.txt
          echo "INPUTS_SHA=$(cat inputs_sha.txt | cut -c1-7)" >> $GITHUB_ENV

      - name: Base OS
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.BENKIRK_DOCKERHUB_USERNAME }}/gh-ci-${{ inputs.os }}:latest
          cache-from: type=registry,ref=${{ secrets.BENKIRK_DOCKERHUB_USERNAME }}/gh-ci-cache-${{ inputs.os }}:buildcache-${{env.INPUTS_SHA }}
          cache-to: type=registry,ref=${{ secrets.BENKIRK_DOCKERHUB_USERNAME }}/gh-ci-cache-${{ inputs.os }}:buildcache-${{env.INPUTS_SHA }},mode=max
          context: containers/devenv
          file: containers/devenv/Dockerfile
          build-args: |
            BASE_OS=${{ inputs.os }}
            COMPILER_FAMILY=os-gcc
            COMPILERS_PREREQ=${{ inputs.conda && 'miniforge' || inputs.os }}
            FINAL_TARGET=os-gcc
          target: final

      - name: Additional Compiler - Cache SHA
        run: |
          cat << EOF >> build_inputs.txt
          compiler: '${{ inputs.compiler }}'
          compiler_version: '${{ inputs.compiler_version }}'
          cuda: '${{ inputs.cuda }}'
          EOF
          echo && echo "Build Inputs:" && cat build_inputs.txt
          shasum build_inputs.txt > inputs_sha.txt
          cat inputs_sha.txt
          echo "INPUTS_SHA=$(cat inputs_sha.txt | cut -c1-7)" >> $GITHUB_ENV

      - name: Additional Compiler
        if: ${{ inputs.compiler != '<disabled>' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.BENKIRK_DOCKERHUB_USERNAME }}/gh-ci-${{ inputs.os }}-${{ inputs.compiler }}:latest
          cache-from: type=registry,ref=${{ secrets.BENKIRK_DOCKERHUB_USERNAME }}/gh-ci-cache-${{ inputs.os }}:buildcache-${{env.INPUTS_SHA }}
          cache-to: type=registry,ref=${{ secrets.BENKIRK_DOCKERHUB_USERNAME }}/gh-ci-cache-${{ inputs.os }}:buildcache-${{env.INPUTS_SHA }},mode=max
          context: containers/devenv
          file: containers/devenv/Dockerfile
          build-args: |
            BASE_OS=${{ inputs.os }}
            COMPILER_FAMILY=${{ inputs.compiler }}
            COMPILERS_PREREQ=${{ inputs.conda && 'miniforge' || inputs.os }}
            GCC_VERSION=${{ inputs.compiler == 'gcc' && inputs.compiler_version || 'none' }}
            FINAL_TARGET=${{ inputs.cuda && 'cuda' || inputs.compiler }}
          target: final

      - name: Add MPI - Cache SHA
        run: |
          cat << EOF >> build_inputs.txt
          mpi: '${{ inputs.mpi }}'
          mpi_version: '${{ inputs.mpi_version }}'
          EOF
          echo && echo "Build Inputs:" && cat build_inputs.txt
          shasum build_inputs.txt > inputs_sha.txt
          cat inputs_sha.txt
          echo "INPUTS_SHA=$(cat inputs_sha.txt | cut -c1-7)" >> $GITHUB_ENV

      - name: Add MPI
        if: ${{ inputs.mpi != '<disabled>' && inputs.compiler != '<disabled>' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.BENKIRK_DOCKERHUB_USERNAME }}/gh-ci-${{ inputs.os }}-${{ inputs.compiler }}-${{ inputs.mpi }}:latest
          cache-from: type=registry,ref=${{ secrets.BENKIRK_DOCKERHUB_USERNAME }}/gh-ci-cache-${{ inputs.os }}:buildcache-${{env.INPUTS_SHA }}
          cache-to: type=registry,ref=${{ secrets.BENKIRK_DOCKERHUB_USERNAME }}/gh-ci-cache-${{ inputs.os }}:buildcache-${{env.INPUTS_SHA }},mode=max
          context: containers/devenv
          file: containers/devenv/Dockerfile
          build-args: |
            BASE_OS=${{ inputs.os }}
            COMPILER_FAMILY=${{ inputs.compiler }}
            COMPILERS_PREREQ=${{ inputs.conda && 'miniforge' || inputs.os }}
            GCC_VERSION=${{ inputs.compiler == 'gcc' && inputs.compiler_version || 'none' }}
            MPI_FAMILY=${{ inputs.mpi }}
            MPI_PREREQ=${{ inputs.cuda && 'cuda' || inputs.compiler }}
            MPICH_VERSION=${{ (inputs.mpi == 'mpich' || inputs.mpi == 'mpich3') && inputs.mpi_version || 'none' }}
            OPENMPI_VERSION=${{ inputs.mpi == 'openmpi' && inputs.mpi_version || 'none' }}
            FINAL_TARGET=fftlibs
          target: final
