name: Build HPC Development Container Image

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Base OS'
        required: true
        default: almalinux9
        type: choice
        options:
          - almalinux8
          - almalinux9
          - leap
          - tumbleweed
          - noble

      include_conda:
        description: 'Include Conda (Miniforge)'
        required: false
        type: boolean

      compiler:
        description: 'Compiler'
        required: true
        default: os-gcc
        type: choice
        options:
          - os-gcc
          - gcc
          - oneapi
          - aocc
          - nvhpc

      compiler_version:
        description: 'Compiler Version'
        #required: true
        type: string

      mpi:
        description: 'MPI'
        required: true
        default: openmpi
        type: choice
        options:
          - opempi
          - mpich
          - mpich3

      mpi_version:
        description: 'MPI Version'
        #required: true
        type: string

jobs:

  build-image:
    name: Build Container Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Create containers/devenv/extras
        run: |
          sudo apt-get update
          sudo apt-get install make
          which make
          pwd
          ls
          make -C containers/devenv extras

      - name: Interrogate Environment
        run: |
          cat /etc/os-release
          uname -a
          env | sort
          df -h
          lscpu

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Pre-build Query Docker Environment
        run: |
          which docker
          docker --version
          docker buildx ls
          docker buildx inspect
          docker buildx du

      - name: Build BaseOS
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: demorepo/myimg:latest
          context: containers/devenv
          file: containers/devenv/Dockerfile
          build-args: |
            BASE_OS=${{ inputs.os }}
            FINAL_TARGET=os-gcc
            OS_GCC_PREREQ=${{ inputs.include_conda && 'miniforge' || inputs.os }}
          target: final

      - name: Build BaseOS + Additional Compiler
        if: ${{ inputs.compiler != '' }}
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: demorepo/myimg:latest
          context: containers/devenv
          file: containers/devenv/Dockerfile
          build-args: |
            BASE_OS=${{ inputs.os }}
            FINAL_TARGET=${{ inputs.compiler }}
            GCC_VERSION=${{ inputs.compiler == 'gcc' && inputs.compiler_version || 'none' }}
            COMPILERS_PREREQ=${{ inputs.include_conda && 'miniforge' || inputs.os }}
          target: final

      - name: Build BaseOS + Additional Compiler + MPI
        if: ${{ inputs.mpi != '' }}
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: demorepo/myimg:latest
          context: containers/devenv
          file: containers/devenv/Dockerfile
          build-args: |
            BASE_OS=${{ inputs.os }}
            FINAL_TARGET=fftlibs
            COMPILER_FAMILY=${{ inputs.compiler_family }}
            GCC_VERSION=${{ inputs.compiler == 'gcc' && inputs.compiler_version || 'none' }}
            COMPILERS_PREREQ=${{ inputs.include_conda && 'miniforge' || inputs.os }}
            MPI_FAMILY=${{ inputs.mpi }}
            MPICH_VERSION=${{ inputs.mpi == 'mpich' && inputs.mpi_version || 'none' }}
            OPENMPI_VERSION=${{ inputs.mpi == 'openmpi' && inputs.mpi_version || 'none' }}
          target: final
