name: Build HPC Development Images

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Base OS'
        type: choice
        required: true
        default: almalinux9
        options:
          - almalinux8
          - almalinux9
          - almalinux10
          - jammy
          - noble
          - leap
          - tumbleweed

      docker_repo:
        description: "Docker Repository for Deployment"
        type: choice
        required: true
        default: "ncarcisl/hpcdev"
        options:
          - "benjaminkirk/gh-ci"
          - "benjaminkirk/hpcdev"
          - "ncarcisl/gh-ci"
          - "ncarcisl/hpcdev"

      test:
        description: 'Test Image'
        type: boolean
        required: false
        default: true

      publish:
        description: 'Publish Image'
        type: boolean
        required: false
        default: false

jobs:

  build-matrix:
    name: Build
    strategy:
      fail-fast: false
      max-parallel: 16
      matrix:
        compiler: [ clang, nvhpc, oneapi, aocc, gcc, gcc12, gcc14 ]
        mpi:      [ openmpi, mpich, mpich3 ]
        gpu:      [ nogpu, cuda ]
        arch:     [ x86_64, aarch64 ]

        include:
          # gpu architecture-dependent build arg specifications
          - arch: x86_64
            gpu: cuda
            gpu_build_args: |
              CUDA_VERSION=12.9
              CUDA_INSTALLER_URL=https://developer.download.nvidia.com/compute/cuda/12.9.1/local_installers/cuda_12.9.1_575.57.08_linux.run

          - arch: aarch64
            gpu: cuda
            gpu_build_args: |
              CUDA_VERSION=12.9
              CUDA_INSTALLER_URL=https://developer.download.nvidia.com/compute/cuda/12.9.1/local_installers/cuda_12.9.1_575.57.08_linux_sbsa.run

          # compiler build arg specifications
          - compiler: gcc
            compiler_build_args: |
              COMPILER_FAMILY=os-gcc

          - compiler: gcc12
            compiler_build_args: |
              COMPILER_FAMILY=gcc
              GCC_VERSION=12.5.0

          - compiler: gcc14
            compiler_build_args: |
              COMPILER_FAMILY=gcc
              GCC_VERSION=14.2.0

          - compiler: oneapi
            compiler_build_args: |
              COMPILER_FAMILY=oneapi
              ONEAPI_VERSION=2025.2.0
              ONEAPI_CC_URL=https://registrationcenter-download.intel.com/akdlm/IRC_NAS/39c79383-66bf-4f44-a6dd-14366e34e255/intel-dpcpp-cpp-compiler-2025.2.0.527_offline.sh
              ONEAPI_FC_URL=https://registrationcenter-download.intel.com/akdlm/IRC_NAS/2c69ab6a-dfff-4d8f-ae1c-8368c79a1709/intel-fortran-compiler-2025.2.0.534_offline.sh

          - compiler: aocc
            compiler_build_args: |
              COMPILER_FAMILY=aocc

          - compiler: nvhpc
            arch: x86_64
            compiler_build_args: |
              COMPILER_FAMILY=nvhpc
              MARCH_FLAGS=-march=x86-64-v3
              NVHPC_VERSION=25.7
              NVHPC_URL=https://developer.download.nvidia.com/hpc-sdk/25.7/nvhpc_2025_257_Linux_x86_64_cuda_12.9.tar.gz

          - compiler: nvhpc
            arch: aarch64
            compiler_build_args: |
              COMPILER_FAMILY=nvhpc
              NVHPC_VERSION=25.7
              NVHPC_URL=https://developer.download.nvidia.com/hpc-sdk/25.7/nvhpc_2025_257_Linux_aarch64_cuda_12.9.tar.gz

          # clang+flang from source always seems to fail on GHA public runners -
          # 16GB of RAM simply isn't enough for flang as of 20.1.8.
          # Need build cloud or caches from CIRRUS
          - compiler: clang
            compiler_build_args: |
              COMPILER_FAMILY=clang
              LLVM_VERSION=21.1.0

          # clang binary packages don't have OpenMP, and X86 requires pretty new libc.so
          # - compiler: clang
          #   arch: x86_64
          #   compiler_build_args: |
          #     COMPILER_FAMILY=clang
          #     LLVM_VERSION=21.1.0
          #     LLVM_URL=https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.0/LLVM-21.1.0-Linux-X64.tar.xz

          # - compiler: clang
          #   arch: aarch64
          #   compiler_build_args: |
          #     COMPILER_FAMILY=clang
          #     LLVM_VERSION=21.1.0
          #     LLVM_URL=https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.0/LLVM-21.1.0-Linux-ARM64.tar.xz

          # mpi build arg specifications
          - mpi: openmpi
            mpi_build_args: |
              MPI_FAMILY=openmpi
              OPENMPI_VERSION=5.0.8

          - mpi: mpich
            mpi_build_args: |
              MPI_FAMILY=mpich
              MPICH_VERSION=4.3.1

          - mpi: mpich3
            mpi_build_args: |
              MPI_FAMILY=mpich3
              MPICH_VERSION=3.4.3

        exclude:
          - arch: aarch64
            compiler: oneapi
          - arch: aarch64
            compiler: aocc
          - arch: aarch64
            mpi: mpich3

          - compiler: nvhpc
            arch: aarch64
            mpi: mpich

          - compiler: clang
            arch: aarch64



    uses: ./.github/workflows/build-hpc-development-image.yaml
    with:
      docker_repo: ${{ inputs.docker_repo }}
      os: ${{ inputs.os }}
      arch: ${{ matrix.arch }}
      runner: ${{ matrix.arch == 'x86_64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
      free_runner_space: true
      conda: true
      gpu: ${{ matrix.gpu }}
      gpu_build_args: ${{ matrix.gpu_build_args }}
      compiler: ${{ matrix.compiler }}
      compiler_build_args: ${{ matrix.compiler_build_args }}
      mpi: ${{ matrix.mpi }}
      mpi_build_args: ${{ matrix.mpi_build_args }}
      test: ${{ inputs.test }}
      publish: ${{ inputs.publish }}
      extra_build_args: |
        HDF5_VERSION=1.14.6
        NETCDF_C_VERSION=4.9.3
        NETCDF_FORTRAN_VERSION=4.6.2
        PNETCDF_VERSION=1.14.0
        PIO_VERSION=2.6.6
        PIO_TAG=pio2_6_6
        FFTW_VERSION=3.3.10
        HEFFTE_VERSION=2.4.1

    secrets:
      dockerhub_token: ${{ secrets.BENKIRK_DOCKERHUB_TOKEN }}
