name: Updated - Build HPC Development Images

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Test Image'
        type: boolean
        required: false
        default: false

      publish:
        description: 'Publish Image'
        type: boolean
        required: false
        default: false

jobs:

  build-matrix:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:       [ almalinux10 ]
        arch:     [ x86_64, aarch64 ]
        gpu:      [ nogpu, cuda ]
        #compiler: [ oneapi, aocc, os-gcc, gcc12, gcc13, gcc14, gcc15 ]
        #mpi:      [ openmpi, mpich, mpich3 ]

        include:

          # gpu build arg specifications -
          - arch: x86_64
            gpu: cuda
            gpu_build_args: |
              CUDA_VERSION=12.9
              CUDA_INSTALLER_URL=https://developer.download.nvidia.com/compute/cuda/12.9.1/local_installers/cuda_12.9.1_575.57.08_linux.run

          - arch: aarch64
            gpu: cuda
            gpu_build_args: |
              CUDA_VERSION=12.9
              CUDA_INSTALLER_URL=https://developer.download.nvidia.com/compute/cuda/12.9.1/local_installers/cuda_12.9.1_575.57.08_linux_sbsa.run



    uses: ./.github/workflows/refactor-hpc-development-image.yaml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      gpu: ${{ matrix.gpu }}
      runner: ${{ matrix.arch == 'x86_64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
      conda: true
      gpu: ${{ matrix.gpu }}
      gpu_build_args: |

      # compiler: ${{ matrix.compiler }}
      # compiler_build_args: ${{ matrix.compiler_build_args }}
      # mpi: ${{ matrix.mpi }}
      # mpi_build_args: ${{ matrix.mpi_build_args }}
      test: ${{ inputs.test }}
      publish: ${{ inputs.publish }}

    secrets:
      dockerhub_token: ${{ secrets.BENKIRK_DOCKERHUB_TOKEN }}
