name: Updated - Build, Test, and Deploy a HPC Development Image

on:
  workflow_call:
    inputs:
      os:
        description: 'Base OS'
        required: false
        type: string
        default: almalinux9

      arch:
        description: 'CPU Architecture'
        required: false
        type: string
        default: 'x86_64'

      runner:
        description: 'GitHub Runner Type'
        required: false
        type: string
        default: 'ubuntu-latest'

      free_runner_space:
        description: 'Remove unneeded software on runner host to free up disk space'
        type: boolean
        required: false
        default: true

      buildx_driver:
        description: 'Docker setup-buildx-action driver type'
        required: false
        type: string
        default: 'docker-container'

      buildx_endpoint:
        description: 'Docker setup-buildx-action endpoint'
        required: false
        type: string
        default: ''

      conda:
        description: 'Include Conda (Miniforge)'
        type: boolean
        required: false
        default: true

      compiler:
        description: 'Compiler'
        type: string
        required: false
        default: 'os-gcc'

      compiler_build_args:
        description: 'Compiler Docker BUILD_ARGS'
        type: string
        required: false

      mpi:
        description: 'MPI'
        type: string
        required: false
        default: 'openmpi'

      mpi_build_args:
        description: 'MPI Docker BUILD_ARGS'
        type: string
        required: false

      gpu:
        description: 'GPU / Accelerator framework'
        type: string
        required: false
        default: 'nogpu'

      gpu_build_args:
        description: 'GPU Docker BUILD_ARGS'
        type: string
        required: false

      extra_build_args:
        description: 'Miscellaneous Docker BUILD_ARGS'
        type: string
        required: false

      test:
        description: 'Test Image'
        type: boolean
        required: false
        default: false

      publish:
        description: 'Publish Image'
        type: boolean
        required: false
        default: false

    secrets:
      dockerhub_token:
        required: true



jobs:

  build-image:
    name: Build, Test, & Publish Image
    runs-on: ${{ inputs.runner }}

    steps:

      - name: Set Image Build Environment Variables
        run: |
          cat << EOF >> ${GITHUB_ENV}
          COMPILER_LABEL=-${{ inputs.compiler == 'os-gcc' && 'gcc' || inputs.compiler }}
          GPU_LABEL=-${{ inputs.gpu }}
          MPI_LABEL=-${{ inputs.mpi }}
          EOF
          cat << EOF > build_inputs.txt
          arch: '${{ inputs.arch }}'
          os: '${{ inputs.os }}'
          compiler: '${{ inputs.compiler }}'
          ${{ inputs.compiler_build_args }}
          mpi: '${{ inputs.mpi }}'
          ${{ inputs.mpi_build_args }}
          gpu: '${{ inputs.gpu }}'
          ${{ inputs.gpu_build_args }}
          ${{ inputs.extra_build_args }}
          EOF
          sed -i '/^[[:space:]]*$/d' build_inputs.txt
          echo && echo "Build Inputs:" && cat build_inputs.txt
          shasum build_inputs.txt > inputs_sha.txt
          cat inputs_sha.txt
          echo "INPUTS_SHA=$(cat inputs_sha.txt | cut -c1-7)" >> ${GITHUB_ENV}
          if [[ "${{ inputs.gpu }}" == "nogpu" ]]; then
              echo "GPU_LABEL=" >> ${GITHUB_ENV}
          fi

      - name: Set Image Tags
        id: tags
        run: |
          CI_CACHE=benjaminkirk/gh-ci-cache-refactor-${{ inputs.os }}:cache-${{ inputs.arch }}-${INPUTS_SHA}
          CI_TAG=benjaminkirk/gh-ci-refactor-${{ inputs.arch }}:${{ inputs.os }}${COMPILER_LABEL}${MPI_LABEL}${GPU_LABEL}-devel
          CI_TAG_DEVEL=${CI_TAG}
          CI_TAG_DEVEL=${CI_TAG_DEVEL//benjaminkirk/ncarcisl}
          CI_TAG_DEVEL=${CI_TAG_DEVEL//-latest/-devel}
          PUBLISH_CACHE=${CI_CACHE//benjaminkirk/ncarcisl}
          PUBLISH_TAG=${CI_TAG_DEVEL//-devel/-latest}
          cat << EOF > tags.sh
          CI_CACHE=${CI_CACHE}
          CI_TAG=${CI_TAG}
          CI_TAG_DEVEL=${CI_TAG_DEVEL}
          PUBLISH_CACHE=${PUBLISH_CACHE}
          PUBLISH_TAG=${PUBLISH_TAG}
          EOF
          cat tags.sh

          cat tags.sh >> ${GITHUB_ENV}
          cat tags.sh >> ${GITHUB_OUTPUT}

      - name: Check out Repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Create containers/refactor/extras
        run: |
          which make 2>/dev/null || { sudo apt-get update && sudo apt-get install make; }
          make -C containers/refactor extras

      - name: Free Disk Space on Runner
        if: ${{ inputs.free_runner_space }}
        uses: ./.github/actions/slim-action-runner

      - name: Interrogate Runner Environment
        run: |
          env | sort && echo
          cat /etc/os-release && echo
          uname -a && echo
          df -h && echo
          lscpu

      - name: Set up Docker BuildX (local)
        if: ${{ inputs.buildx_endpoint == '' }}
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ inputs.arch == 'x86_64' && 'linux/amd64' || 'linux/arm64' }}

      - name: Set up Docker BuildX (remote)
        if: ${{ inputs.buildx_endpoint != '' }}
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ inputs.arch == 'x86_64' && 'linux/amd64' || 'linux/arm64' }}
          driver: ${{ inputs.buildx_driver }}
          endpoint: ${{ inputs.buildx_endpoint }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: benjaminkirk
          password: ${{ secrets.dockerhub_token }}

      - name: Query Docker Environment
        run: |
          which docker
          docker --version
          docker buildx ls
          docker buildx inspect
          docker buildx du

      # - name: Base OS + Toolkits
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: false
      #     tags: ${{ env.CI_TAG }}
      #     cache-from: type=registry,ref=benjaminkirk/gh-ci-cache-refactor-${{ inputs.os }}:cache-${{ inputs.arch }}-${{env.INPUTS_SHA }}
      #     cache-to: type=registry,ref=benjaminkirk/gh-ci-cache-refactor-${{ inputs.os }}:cache-${{ inputs.arch }}-${{ env.INPUTS_SHA }},mode=max
      #     context: containers/refactor
      #     file: containers/refactor/Dockerfile
      #     build-args: |
      #       BASE_OS=${{ inputs.os }}
      #       FINAL_TARGET=toolkits
      #       MINIFORGE_PREREQ=${{ inputs.gpu == 'cuda' && 'cuda' || 'base_os' }}
      #       ${{ inputs.extra_build_args }}
      #       ${{ inputs.gpu_build_args }}
      #     target: final

      - name: BaseOS + Toolkits + Compiler + MPI Image
        uses: docker/build-push-action@v6
        with:
          push: true
          load: true
          tags: ${{ env.CI_TAG }}
          cache-from: type=registry,ref=${{env.CI_CACHE }}
          cache-to: type=registry,ref=${{ env.CI_CACHE }},mode=max
          context: containers/refactor
          file: containers/refactor/Dockerfile
          target: final
          build-args: |
            BASE_OS=${{ inputs.os }}
            FINAL_TARGET=fftlibs
            MINIFORGE_PREREQ=${{ inputs.gpu == 'cuda' && 'cuda' || 'base_os' }}
            ${{ inputs.extra_build_args }}
            ${{ inputs.gpu_build_args }}
            ${{ inputs.compiler_build_args }}
            ${{ inputs.mpi_build_args }}

      - name: Query Post-Build Disk Usage
        run: |
          df -h
          docker image ls
          docker image inspect ${{ env.CI_TAG }}
          docker buildx du

      - name: Test Image
        if: ${{ inputs.test }}
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          push: false
          tags: local:test
          cache-from: type=registry,ref=${{env.CI_CACHE }}
          context: containers/test
          file: containers/test/Dockerfile
          target: test
          build-args: |
            BASE_IMAGE=${{ env.CI_TAG }}
            TEST_SCRIPTS=/container/extras/build_osu-micro-benchmarks.sh:/container/extras/build_dart.sh:/container/extras/build_kokkos.sh

      - name: Publish Image
        if: ${{ inputs.publish && inputs.test }}
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          push: true
          tags: ${{ env.CI_TAG_DEVEL }}
          cache-from: type=registry,ref=${{env.PUBLISH_CACHE }}
          cache-to: type=registry,ref=${{ env.PUBLISH_CACHE }},mode=max
          context: containers/publish
          file: containers/publish/Dockerfile
          build-args: |
            BASE_IMAGE=${{ env.CI_TAG }}
            DEPLOYMENT_SCRIPTS=/container/extras/build_osu-micro-benchmarks.sh
          target: final

    outputs:
      CI_TAG: ${{ steps.tags.outputs.CI_TAG }}
      PUBLISH_TAG: ${{ steps.tags.outputs.PUBLISH_TAG }}
      INPUTS_SHA: ${{ steps.tags.outputs.INPUTS_SHA }}
