name: Trigger Workflows

on:
  workflow_dispatch:
  schedule:
    # run at 3:43 UTC 15th of each month
    # ref: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onschedule
    - cron: '43 3 15 * *'


jobs:
  trigger-workflows:
    name: Trigger Workflows
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -elo pipefail {0}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - uses: actions4gh/setup-gh@v1.0.2
        with:
          gh-version: latest
          token: ${{ secrets.BENKIRK_GITHUB_TOKEN }}
          github-server-url: https://github.com

      - name: Almalinux9
        run: |
          gh workflow run matrix-build-images.yaml -f os=almalinux9 -f test=false -f publish=false

      - name: Ubuntu Noble
        run: |
          gh workflow run matrix-build-images.yaml -f os=noble -f test=false -f publish=false

      - name: OpenSUSE Leap
        run: |
          gh workflow run matrix-build-images.yaml -f os=leap -f test=false -f publish=false
