name: Trigger Workflows

on:
  workflow_dispatch:
  schedule:
    # run at 3:43 UTC 15th of each month
    # ref: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onschedule
    - cron: '43 3 7 * *'


jobs:
  trigger-workflows:
    name: Trigger Workflows
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -elo pipefail {0}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - uses: actions4gh/setup-gh@v1.0.2
        with:
          gh-version: latest
          token: ${{ secrets.BENKIRK_GITHUB_TOKEN }}
          github-server-url: https://github.com
      - run: gh status
        env:
          GH_REPO: ${{ github.repository }}
          BODY: Hello world!
